version: "3.9"
services:
    openscad-jupyter:
      image: donnellans/openscad-jupyter:latest
      container_name: openscad-jupyter
      ports:
        - "8888:8888"
      restart: always
      build: .
      volumes:
      - ./3d-projects:/home/openscad/data:rw